---
- name: set package facts
  set_fact:
    dst_path: "/media/{{ lbu_media }}/go2rtc"
    local_version: "{{ local_version.stdout.splitlines()[0] }}"
    remote_version: "{{ remote_version.stdout.splitlines()[0] }}"

- name: remount,rw for /media/{{ lbu_media }}
  ansible.builtin.raw: mount -oremount,rw /media/{{ lbu_media }}

- name: stop go2rtc
  ansible.builtin.raw: rc-service go2rtc stop

- name: update go2rtc {{ local_version }} -> {{ remote_version }}
  ansible.builtin.raw: |
    wget https://github.com/AlexxIT/go2rtc/releases/download/v{{ remote_version }}/go2rtc_linux_armv6 -O {{ dst_path }}
    sync

- name: remount,ro for /media/{{ lbu_media }}
  ansible.builtin.raw: mount -oremount,ro /media/{{ lbu_media }}

- name: start go2rtc
  ansible.builtin.raw: rc-service go2rtc start

- name: check if running properly
  ansible.builtin.raw: pgrep go2rtc
