# before use:
#   mkfs.vfat /dev/sda1
#   mount /dev/sda1 /mnt/tmp 
#   tar xzfp alpine-rpi-3.x.y-armhf.tar.gz -C /mnt/tmp
#   cp hostname.apkovl.tar.gz /mnt/tmp
#   umount /dev/sda1
---
- name: camera setup for alpine host(s)
  hosts: node.local
  gather_facts: no
  serial: 1

  tasks:
    - name: disable crond
      block:
        - name: stop crond
          ansible.builtin.raw: service crond stop

        - name: stop crond on boot
          ansible.builtin.raw: rc-update del crond

    - name: disable wireless power_save
      block:
        - name: set wireless power_save to off
          ansible.builtin.raw: iw wlan0 set power_save off

        - name: add wlan power_save rule
          ansible.builtin.raw: echo 'ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan*", RUN+="/usr/sbin/iw $name set power_save off"' > /etc/udev/rules.d/powersave.rules

        - name: add to lbu
          ansible.builtin.raw: lbu add /etc/udev/rules.d/powersave.rules


    - name: disable IPv6
      block:
        - name: check disable_ipv6 presence
          ansible.builtin.raw: grep "net.ipv6.conf.all.disable_ipv6" /etc/sysctl.conf | cat
          register: IPV6_STATUS

        - name: update disable_ipv6 config
          ansible.builtin.raw: sed -i -e 's/^net.ipv6.conf.all.disable_ipv6.*/net.ipv6.conf.all.disable_ipv6 = 1/g' /etc/sysctl.conf; sysctl -p
          when: IPV6_STATUS.stdout.splitlines()|length == 1

        - name: set disable_ipv6 config
          ansible.builtin.raw: echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf; sysctl -p
          when: IPV6_STATUS.stdout.splitlines()|length == 0


    - name: lbu media stuff
      block:
        - name: get $LBU_MEDIA location
          ansible.builtin.raw: . /etc/lbu/lbu.conf; echo $LBU_MEDIA
          register: LBU_MEDIA

        - meta: end_host
          when: LBU_MEDIA.stdout.splitlines()|length != 1

        - name: set $LBU_MEDIA fact
          set_fact:
              lbu_media: "{{ LBU_MEDIA.stdout.splitlines()[0] }}"

        - name: remount,rw for /media/{{ lbu_media }}
          ansible.builtin.raw: mount -oremount,rw /media/{{ lbu_media }}

        - name: setup usercfg.txt
          block:
            - name: usercfg.txt - limit CPU frequency
              ansible.builtin.raw: echo "arm_freq=800" > /media/{{ lbu_media }}/usercfg.txt

            - name: usercfg.txt - enable camera
              ansible.builtin.raw: echo -e "dtoverlay=vc4-fkms-v3d\ncamera_auto_detect=1" >> /media/{{ lbu_media }}/usercfg.txt

        - name: fetch go2rtc
          block:
            - name: stop go2rtc
              ansible.builtin.raw: service go2rtc stop | cat

            - name: get go2rtc version
              ansible.builtin.raw: wget -q "https://api.github.com/repos/AlexxIT/go2rtc/releases/latest" -O- | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | awk '{print(substr($1,2))}'
              register: go2rtc_version

            - name: "download go2rtc v{{ go2rtc_version.stdout.splitlines()[0] }}"
              ansible.builtin.raw: wget https://github.com/AlexxIT/go2rtc/releases/download/v{{ go2rtc_version.stdout.splitlines()[0] }}/go2rtc_linux_armv6 -O /media/{{ lbu_media }}/go2rtc

        - name: remount,ro for /media/{{ lbu_media }}
          ansible.builtin.raw: mount -oremount,ro /media/{{ lbu_media }}

    - name: setup v4l2
      block:
        - name: v4l2 module configuration
          ansible.builtin.raw: echo -e "bcm2835-v4l2\noptions bcm2835-v4l2 max_video_width=3240 max_video_height=2464" > /etc/modules-load.d/rpi-camera.conf

        - name: add v4l2 to lbu
          ansible.builtin.raw: lbu add /etc/modules-load.d/rpi-camera.conf

    - name: apk stuff
      block:
        - name: enable community repository
          ansible.builtin.raw: sed -i -e "/alpine\/v\(.*\)community/ s/# *//" /etc/apk/repositories;

        - name: apk update
          ansible.builtin.raw: apk update

        - name: setup apk cache
          ansible.builtin.raw: setup-apkcache /media/{{ lbu_media }}/cache


    - name: install libcamera-apps
      block:
        - name: download libcamera-apps
          ansible.builtin.raw: wget https://raw.githubusercontent.com/nekoserv-repository/packages/main/alpinelinux/libcamera-apps-1.2.1-r0.apk -O /tmp/libcamera-apps-1.2.1-r0.apk

        - name: install libcamera-apps
          ansible.builtin.raw: apk add --allow-untrusted /tmp/libcamera-apps-1.2.1-r0.apk

        - name: install libcamera-raspberrypi
          ansible.builtin.raw: apk add libcamera-raspberrypi

        - name: install tools
          ansible.builtin.raw: apk add nano htop

        - name: setup udev
          ansible.builtin.raw: setup-devd udev

    - name: go2rtc initscript
      block:
        - name: create go2rtc.yaml
          ansible.builtin.raw: echo -e "streams:\n  cam\x3A    exec:libcamera-vid --nopreview -t 0 --width 1280 --height 720 --framerate 20 --inline -o -" > /etc/go2rtc.yaml

        - name: create go2rtc initscript
          ansible.builtin.raw: echo -e "#!/sbin/openrc-run\nname=\"go2rtc daemon\"\ncommand_background=\"yes\"\ndepend() {\n    need net\n}\nstart() {\n    /media/{{ lbu_media }}/go2rtc -config /etc/go2rtc.yaml 2>&1 > /dev/null &\n}\nstop() {\n    pkill -x /media/{{ lbu_media }}/go2rtc | cat\n}" > /etc/init.d/go2rtc

        - name: set chmod
          ansible.builtin.raw: chmod 0700 /etc/init.d/go2rtc

        - name: add to boot
          ansible.builtin.raw: rc-update add go2rtc default

        - name: add to lbu
          ansible.builtin.raw: lbu add /etc/init.d/go2rtc

        - name: save
          ansible.builtin.raw: lbu ci

        - name: sync
          ansible.builtin.raw: sync

    - name: reboot
      block:
        - name: reboot
          ansible.builtin.raw: reboot
          poll: 0
          ignore_errors: yes

        - name: wait for host to come up
          wait_for:
            host: "{{ inventory_hostname }}"
            port: 22
            state: started
            delay: 30
            timeout: 120
          delegate_to: localhost
