---
# file: update.yml

## updates in parallel
- hosts: alpine
  gather_facts: no
  roles:
    - alpine-update
- hosts: debian
  roles:
    - debian-update

## reboot checks in serial
- hosts: alpine
  gather_facts: no
  serial: 1
  roles:
    - alpine-reboot
- hosts: debian
  serial: 1
  roles:
    - debian-reboot
