---
- name: get traefik path
  ansible.builtin.raw: dirname $(which traefik)
  register: which_traefik

- name: set facts - traefik_path, version
  set_fact:
    traefik_path: "{{ which_traefik.stdout.splitlines()[0] }}"
    version: "{{ remote_version.stdout.splitlines()[0] }}"

- name: download traefik v{{ version }}
  ansible.builtin.raw: |
    wget https://github.com/traefik/traefik/releases/download/v{{ version }}/traefik_v{{ version }}_linux_amd64.tar.gz -O- | tar -C {{ traefik_path }} -zx traefik
    sync

- name: restart traefik
  ansible.builtin.raw: rc-service traefik restart

- name: check if running properly
  ansible.builtin.raw: pgrep traefik
