---
- name: get traefik path
  ansible.builtin.raw: dirname $(which traefik)
  register: which_traefik

- name: set package facts
  set_fact:
    dst_path: "{{ which_traefik.stdout.splitlines()[0] }}"
    local_version: "{{ local_version.stdout.splitlines()[0] }}"
    remote_version: "{{ remote_version.stdout.splitlines()[0] }}"

- name: update traefik {{ local_version }} -> {{ remote_version }}
  ansible.builtin.raw: |
    wget https://github.com/traefik/traefik/releases/download/v{{ remote_version }}/traefik_v{{ remote_version }}_linux_amd64.tar.gz -O- | tar -C {{ dst_path }} -zx traefik
    sync

- name: restart traefik
  ansible.builtin.raw: rc-service traefik restart

- name: check if running properly
  ansible.builtin.raw: pgrep traefik
