---
- name: check if reboot needed
  ansible.builtin.raw: lsof / 2>&1 | awk '$3=="(deleted)"' | cat
  changed_when: false
  register: lsof_output

- name: reboot not required
  ansible.builtin.meta: end_host
  when: lsof_output.stdout.splitlines()|length == 0

- name: reboot now
  ansible.builtin.raw: reboot
  poll: 0
  ignore_errors: yes

- name: wait for host to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 120
  delegate_to: localhost
