---
- name: check if reboot needed
  ansible.builtin.raw: lsof / 2>&1 | awk '$3=="(deleted)"' | cat
  changed_when: false
  register: files_output

- name: reboot check - initramfs update
  ansible.builtin.raw: if [ -f /boot/initramfs* ]; then find /boot/initramfs* -mmin -2 2>/dev/null; fi
  changed_when: false
  register: initramfs_output

- name: reboot not required
  ansible.builtin.meta: end_host
  when:
    - files_output.stdout.splitlines()|length == 0
    - initramfs_output.stdout.splitlines()|length == 0

- name: rebooting {{ inventory_hostname }}
  ansible.builtin.raw: reboot
  poll: 0
  ignore_errors: yes

- name: wait for {{ inventory_hostname }} to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 120
  delegate_to: localhost
