---
- name: update index of available package(s)
  ansible.builtin.raw: apk update

- name: check package(s) update(s)
  ansible.builtin.raw: apk version -l '<'
  register: pkgs_output

- name: nothing to upgrade
  ansible.builtin.raw: echo
  when: pkgs_output.stdout.splitlines()|length == 1

- meta: end_host
  when: pkgs_output.stdout.splitlines()|length == 1

- name: package(s) to be upgraded
  ansible.builtin.debug:
    msg: "{{ pkgs_output.stdout_lines }}"

- name: upgrading {{ pkgs_output.stdout.splitlines()|length - 1 }} package(s)...
  ansible.builtin.raw: apk upgrade

- name: check if adhosts.conf exists
  ansible.builtin.raw: ls /etc/unbound/adhosts.conf > /dev/null | cat
  register: stat_result

- name: run local backup utility (lbu)
  ansible.builtin.raw: mv /etc/unbound/adhosts.conf /tmp/adhosts.conf ; touch /etc/unbound/adhosts.conf ; lbu ci ; mv /tmp/adhosts.conf /etc/unbound/adhosts.conf
  when: stat_result.stdout_lines|length == 0
