---
- name: update index of available package(s)
  ansible.builtin.raw: apk update

- name: check package(s) update(s)
  ansible.builtin.raw: apk version -l '<'
  changed_when: pkgs_output.stdout.splitlines()|length > 1
  failed_when: pkgs_output.stdout.splitlines()|length == 0
  register: pkgs_output

- name: system update
  when: pkgs_output.stdout.splitlines()|length > 1
  ansible.builtin.include_tasks: system-update.yml
