---
- name: update debian host(s)
  hosts: debian
  serial: 1

  tasks:
    - name: update index of available package(s)
      apt:
        update_cache: true

    - name: check package(s) update(s)
      ansible.builtin.raw: apt-get -s upgrade | grep '^Inst ' | cat
      register: pkgs_output

    - meta: end_play
      when: pkgs_output.stdout.splitlines()|length == 0

    - name: package(s) to be upgraded
      ansible.builtin.debug:
        msg: "{{ pkgs_output.stdout_lines }}"
      when: pkgs_output.stdout.splitlines()|length > 0

    - name: update package(s) to latest version(s)
      apt:
        name: "*"
        state: latest

    - name: check if reboot needed
      ansible.builtin.raw: lsof / 2>&1 | awk '$4=="DEL"' | cat
      register: lsof_output

    - name: reboot if needed
      ansible.builtin.reboot:
      when: lsof_output.stdout.splitlines()|length > 0
