---
- name: update debian host(s)
  hosts: debian
  serial: 1

  tasks:
    - name: update index of available package(s)
      apt:
        update_cache: true

    - name: check package(s) update(s)
      ansible.builtin.raw: apt-get -s upgrade | grep '^Inst ' | cat
      register: upd_output

    - name: check dist-upgrade(s)
      ansible.builtin.raw: apt-get -s dist-upgrade | grep '^Inst ' | cat
      register: upgd_output

    - meta: end_host
      when:
        - upd_output.stdout.splitlines()|length == 0
        - upgd_output.stdout.splitlines()|length == 0

    - name: package(s) to be updated
      ansible.builtin.debug:
        msg: "{{ upd_output.stdout_lines }}"
      when: upd_output.stdout.splitlines()|length > 0

    - name: package(s) to be upgraded
      ansible.builtin.debug:
        msg: "{{ upgd_output.stdout_lines }}"
      when: upgd_output.stdout.splitlines()|length > 0

    - name: updating package(s) to latest version(s)
      apt:
        name: "*"
        state: latest

    - name: check if reboot required by package(s) update(s)
      ansible.builtin.raw: lsof / 2>&1 | awk '$4=="DEL"' | cat
      register: lsof_output

    - name: rebooting
      ansible.builtin.reboot:
      when: (lsof_output.stdout.splitlines()|length > 0) or (upgd_output.stdout.find('linux-image') != -1)
