---
- name: update index of available package(s)
  apt:
    update_cache: true

- name: check upgrade(s)
  ansible.builtin.raw: apt-get -s upgrade | grep '^Inst ' | cat
  changed_when: upg_output.stdout.splitlines()|length > 0
  register: upg_output

- name: check dist-upgrade(s)
  ansible.builtin.raw: apt-get -s dist-upgrade | grep '^Inst ' | cat
  changed_when: dist_upg_output.stdout.splitlines()|length > 0
  register: dist_upg_output

- name: nothing to upgrade
  ansible.builtin.meta: end_host
  when:
    - upg_output.stdout.splitlines()|length == 0
    - dist_upg_output.stdout.splitlines()|length == 0

- name: package(s) to be upgraded
  ansible.builtin.debug:
    msg: "{{ upg_output.stdout_lines }}"
  changed_when: false

- name: package(s) to be dist-upgraded
  ansible.builtin.debug:
    msg: "{{ dist_upg_output.stdout_lines }}"
  changed_when: false

- name: upgrading package(s) to latest version(s)
  apt:
    name: "*"
    state: latest
