---
- name: reboot check - deleted map files
  ansible.builtin.raw: lsof / 2>&1 | awk '$4=="DEL"' | cat
  changed_when: false
  register: map_output

- name: reboot check - deleted files
  ansible.builtin.raw: lsof / 2>&1 | awk '$10=="(deleted)"' | cat
  changed_when: false
  register: files_output

- name: reboot check - new kernel
  ansible.builtin.raw: readlink /vmlinuz | awk '!/'"$(uname -r)"'/'
  changed_when: false
  register: kernel_output

- name: reboot check - initrd update
  ansible.builtin.raw: find /boot/initrd* -mmin -2
  changed_when: false
  register: initrd_output

- name: skip-me if reboot required
  ansible.builtin.meta: end_host
  when:
    - map_output.stdout.splitlines()|length == 0
    - files_output.stdout.splitlines()|length == 0
    - kernel_output.stdout.splitlines()|length == 0
    - initrd_output.stdout.splitlines()|length == 0

- name: rebooting {{ inventory_hostname }}
  ansible.builtin.reboot:
