---
- name: reboot check for apps
  ansible.builtin.raw: lsof / 2>&1 | awk '$4=="DEL"' | cat
  register: lsof_output

- name: reboot check for new kernel
  ansible.builtin.raw: readlink /vmlinuz | awk '!/'"$(uname -r)"'/'
  register: kernel_output

- meta: end_host
  when: (lsof_output.stdout.splitlines()|length == 0) and (kernel_output.stdout.splitlines()|length == 0)

- name: rebooting
  ansible.builtin.reboot:
