---
- name: reboot check for apps
  ansible.builtin.raw: lsof / 2>&1 | awk '$4=="DEL"' | cat
  changed_when: false
  register: lsof_output

- name: reboot check for new kernel
  ansible.builtin.raw: readlink /vmlinuz | awk '!/'"$(uname -r)"'/'
  changed_when: false
  register: kernel_output

- name: reboot check for initrd update
  ansible.builtin.raw: find /boot/initrd* -mmin -2
  changed_when: false
  register: initrd_output

- name: reboot not required
  ansible.builtin.meta: end_host
  when:
    - lsof_output.stdout.splitlines()|length == 0
    - kernel_output.stdout.splitlines()|length == 0
    - initrd_output.stdout.splitlines()|length == 0

- name: rebooting {{ inventory_hostname }}
  ansible.builtin.reboot:
