---
- name: stop all services
  community.docker.docker_compose:
    project_src: "{{ docker_dir }}"
    state: absent
    remove_orphans: true

- name: prune everything
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true

- name: pull and (re)create services
  community.docker.docker_compose:
    project_src: "{{ docker_dir }}"
    services: "{{ service_name }}"
